[meta:M]
[ = M-[
] = M-]
semicolon = M-semicolon
enter = M-enter
, = M-,
. = escape
space = M-space
a = home
b = left
d = delete
e = end
f = right
h = backspace
k = macro(S-end delete)
n = down
p = up
t = tab
u = macro(S-home delete)

[meta+shift]
[ = M-S-[
] = M-S-]
semicolon = M-S-semicolon
' = M-S-'
enter = M-S-enter
, = M-S-,
. = M-S-.
space = M-S-space
a = M-S-a
b = M-S-b
c = M-S-c
d = M-S-d
e = M-S-e
f = M-S-f
g = M-S-g
h = M-S-h
i = M-S-i
j = M-S-j
k = M-S-k
l = M-S-l
m = M-S-m
n = M-S-n
o = M-S-o
p = M-S-p
q = M-S-q
r = M-S-r
s = M-S-s
t = S-tab
u = M-S-u
v = M-S-v
w = M-S-w
x = M-S-x
y = M-S-y
z = M-S-z

[ctrl:c]
[ = S-9
] = S-0
semicolon = minus
' = grave
enter = C-enter
space = 0
, = 2
. = 3
a = S-2
b = S-1
c = S-6
d = S-4
e = S-7
h = S-3
i = 8
j = 4
k = 5
l = 6
m = 1
o = 9
p = S-equal
q = S-/
s = S-8
slash = equal
t = S-grave
u = 7
v = |
x = S-5
y = S-minus

[ctrl+shift]
[ = C-S-[
] = C-S-]
semicolon = C-S-semicolon
' = C-S-'
enter = C-S-enter
, = C-S-,
. = C-S-.
space = C-S-space
a = C-a
b = C-S-b
c = C-S-c
d = C-S-d
e = C-S-e
f = C-S-f
g = C-S-g
h = C-S-h
i = C-S-i
j = C-S-j
k = C-S-k
l = C-S-l
m = C-S-m
n = C-S-n
o = C-S-o
p = C-S-p
q = C-S-q
r = C-S-r
s = C-S-s
t = C-S-t
u = C-S-u
v = C-S-v
w = C-S-w
x = C-x
y = C-S-y
z = C-S-z

[meta+ctrl]
[ = M-C-[
] = M-C-]
semicolon = M-C-semicolon
' = M-C-'
enter = M-C-enter
, = M-C-,
. = M-C-.
space = M-C-space
a = M-C-a
b = M-C-b
c = M-C-c
d = M-C-d
e = M-C-e
f = M-C-f
g = M-C-g
h = M-C-h
i = M-C-i
j = M-C-j
k = M-C-k
l = M-C-l
m = M-C-m
n = M-C-n
o = M-C-o
p = M-C-p
q = M-C-q
r = M-C-r
s = M-C-s
t = M-C-t
u = M-C-u
v = M-C-v
w = M-C-w
x = M-C-x
y = M-C-y
z = M-C-z

[ids]
* = *

[main]
# Physical remapping
control = layer(meta)
meta = layer(ctrl)

# Disable extra keys
esc = noop
1 = noop
2 = noop
3 = noop
4 = noop
5 = noop
6 = noop
7 = noop
8 = noop
9 = noop
0 = noop
minus = noop
equal = noop
backslash = noop
grave = noop
tab = noop
backspace = noop
delete = noop
left = noop
up = noop
right = noop
down = noop

[shift]
slash = backslash
