[options]
HoldPkg = pacman glibc
Architecture = auto
SigLevel = Required DatabaseNever
LocalFileSigLevel = Optional

[core]
SigLevel = Required DatabaseNever
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = Required DatabaseNever
Include = /etc/pacman.d/mirrorlist

[multilib]
SigLevel = Required DatabaseNever
Include = /etc/pacman.d/mirrorlist

